/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.AWTException;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.SystemTray;
import java.awt.Toolkit;
import java.awt.TrayIcon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import net.glxn.qrgen.QRCode;
import net.glxn.qrgen.image.ImageType;

/**
 *
 * @author Andy_Antunes
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public TelaPrincipal() {
        initComponents();
        
        setIcon();
        
        setConfDefault();
        
        sendNotification();
                
    }
 
    public void initialize() {
        
        // Teste para verificar se o recurso é suportado
        if (SystemTray.isSupported()) {

            // Criando variável e capturando a imagem do ícone
            Image trayImage = Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("/Imagens/tray.gif"));

            // Mensagem exibida ao passar o mouse sobre o íncone da bandeija
            TrayIcon tray = new TrayIcon(trayImage, "Tray Icon Example");
            SystemTray sysTray = SystemTray.getSystemTray();

            // Action de duplo clique no ícone
            tray.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    // Maximizando a tela
                    new TelaPrincipal().setVisible(true);
                    // Tirando o ícone do System Tray
                    sysTray.remove(tray);
                }
            });

            // Redimensionamento da imagem do ícone
            tray.setImageAutoSize(true);

            // Tratamento de erros
            try {
                sysTray.add(tray);
            } catch (AWTException e) {
                e.printStackTrace();
            }
            // Mensagem exibida quando o programa vai para segundo plano
            tray.displayMessage("Trabalhando em segundo plano.", "Clique aqui para abrir mais detalhes", TrayIcon.MessageType.INFO);
        } else {
            // Caso o System Tray não seja suportado
            JOptionPane.showMessageDialog(null, "Recurso não disponível.");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLimparNome = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelNomeArquivo = new javax.swing.JLabel();
        txtParaNome = new javax.swing.JTextField();
        jPanelVisualizador = new javax.swing.JPanel();
        jPanelPrincipal = new javax.swing.JPanel();
        jPanelFormatoImagem = new javax.swing.JPanel();
        pngBox = new javax.swing.JCheckBox();
        jpgBox = new javax.swing.JCheckBox();
        jLabelTamanhoImagem = new javax.swing.JLabel();
        jSliderTamanhoImagem = new javax.swing.JSlider();
        jLabelConteudoQR = new javax.swing.JLabel();
        jScrollPane1ConteudoQR = new javax.swing.JScrollPane();
        txtParaQrCode = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnGerarQrCode = new javax.swing.JButton();
        btnLimparTexto = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuArquivo = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuInfo = new javax.swing.JMenu();
        jMenuItemSobre = new javax.swing.JMenuItem();

        btnLimparNome.setText("Limpar Nome");
        btnLimparNome.setOpaque(false);
        btnLimparNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparNomeActionPerformed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/help.png"))); // NOI18N
        jLabel2.setToolTipText("Função desativada");

        jLabelNomeArquivo.setText(" Nome do Arquivo");

        txtParaNome.setEditable(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("LTA Service");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelVisualizador.setBackground(new java.awt.Color(255, 255, 255));
        jPanelVisualizador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanelVisualizadorLayout = new javax.swing.GroupLayout(jPanelVisualizador);
        jPanelVisualizador.setLayout(jPanelVisualizadorLayout);
        jPanelVisualizadorLayout.setHorizontalGroup(
            jPanelVisualizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );
        jPanelVisualizadorLayout.setVerticalGroup(
            jPanelVisualizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 246, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelVisualizador, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 75, 250, 250));

        jPanelPrincipal.setBackground(new java.awt.Color(121, 147, 255));
        jPanelPrincipal.setPreferredSize(new java.awt.Dimension(640, 400));
        jPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFormatoImagem.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Formato da Imagem", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 10))); // NOI18N
        jPanelFormatoImagem.setOpaque(false);

        pngBox.setText("PNG");
        pngBox.setOpaque(false);
        pngBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pngBoxActionPerformed(evt);
            }
        });

        jpgBox.setText("JPG");
        jpgBox.setOpaque(false);
        jpgBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpgBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelFormatoImagemLayout = new javax.swing.GroupLayout(jPanelFormatoImagem);
        jPanelFormatoImagem.setLayout(jPanelFormatoImagemLayout);
        jPanelFormatoImagemLayout.setHorizontalGroup(
            jPanelFormatoImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormatoImagemLayout.createSequentialGroup()
                .addComponent(pngBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpgBox)
                .addContainerGap())
        );
        jPanelFormatoImagemLayout.setVerticalGroup(
            jPanelFormatoImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormatoImagemLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanelFormatoImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pngBox)
                    .addComponent(jpgBox))
                .addGap(10, 10, 10))
        );

        jPanelPrincipal.add(jPanelFormatoImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 58, -1, -1));

        jLabelTamanhoImagem.setText("Tamanho da imagem em (cm)");
        jPanelPrincipal.add(jLabelTamanhoImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jSliderTamanhoImagem.setMajorTickSpacing(1);
        jSliderTamanhoImagem.setMaximum(10);
        jSliderTamanhoImagem.setMinimum(1);
        jSliderTamanhoImagem.setPaintLabels(true);
        jSliderTamanhoImagem.setOpaque(false);
        jPanelPrincipal.add(jSliderTamanhoImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 160, -1, -1));

        jLabelConteudoQR.setText("Conteúdo do QR Code");
        jPanelPrincipal.add(jLabelConteudoQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 218, -1, -1));

        txtParaQrCode.setColumns(20);
        txtParaQrCode.setLineWrap(true);
        txtParaQrCode.setRows(5);
        txtParaQrCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtParaQrCodeKeyReleased(evt);
            }
        });
        jScrollPane1ConteudoQR.setViewportView(txtParaQrCode);

        jPanelPrincipal.add(jScrollPane1ConteudoQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 238, 330, 70));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/help.png"))); // NOI18N
        jLabel1.setToolTipText("Digite a sua URL  (http://exemplo.com.br)");
        jPanelPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 258, 30, 30));

        btnGerarQrCode.setText("Gerar QR Code");
        btnGerarQrCode.setOpaque(false);
        btnGerarQrCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarQrCodeActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(btnGerarQrCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 318, -1, -1));

        btnLimparTexto.setText("Limpar Texto");
        btnLimparTexto.setOpaque(false);
        btnLimparTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparTextoActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(btnLimparTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 318, -1, -1));

        jLabelFundo.setBackground(new java.awt.Color(134, 154, 237));
        jLabelFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo.png"))); // NOI18N
        jLabelFundo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelFundo.setMaximumSize(new java.awt.Dimension(32, 14));
        jLabelFundo.setMinimumSize(new java.awt.Dimension(32, 14));
        jLabelFundo.setPreferredSize(new java.awt.Dimension(32, 14));
        jPanelPrincipal.add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 400));

        getContentPane().add(jPanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 400));

        jMenuArquivo.setText("Arquivo");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuArquivo.add(jMenuItemSair);

        jMenuBar.add(jMenuArquivo);

        jMenuInfo.setText("Informações");

        jMenuItemSobre.setText("Sobre");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenuInfo.add(jMenuItemSobre);

        jMenuBar.add(jMenuInfo);

        setJMenuBar(jMenuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        new TelaSobre().setVisible(true);
    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    private void pngBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pngBoxActionPerformed
        if(pngBox.isSelected())
        //Seta 175 e 225 como falso p/ nao poder selecionar ais de uma opção
        jpgBox.setSelected(false);
        //Seta 125 como verdadeiro p/ não poder desmarcar clicando nele mesmo
        pngBox.setSelected(true);
    }//GEN-LAST:event_pngBoxActionPerformed

    private void jpgBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpgBoxActionPerformed
        if(jpgBox.isSelected())
        //Seta 175 e 225 como falso p/ nao poder selecionar ais de uma opção
        pngBox.setSelected(false);
        //Seta 125 como verdadeiro p/ não poder desmarcar clicando nele mesmo
        jpgBox.setSelected(true);
    }//GEN-LAST:event_jpgBoxActionPerformed

    private void btnLimparNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparNomeActionPerformed
        txtParaNome.setText(null);
    }//GEN-LAST:event_btnLimparNomeActionPerformed

    private void btnGerarQrCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarQrCodeActionPerformed
        int size = 0;
        //String extArq = "";
        String extArqNome = "";
        float px = 37.795275590551f;
        int cm = jSliderTamanhoImagem.getValue();
        //String conteudoArquivo = txtParaQrCode.getText();
        //String tituloArquivo = txtParaNome.getText();

        if (/*!"".equals(txtParaNome.getText()) &&*/ !"".equals(txtParaQrCode.getText())) {
            //Condições para setar a extensão da imagem
            if (pngBox.isSelected()) {
                extArqNome = ".png";
            }else if (jpgBox.isSelected()) {
                extArqNome = ".jpg";
            }

            /*
            //Condições para setar a extensão da imagem
            if (pngBox.isSelected()) {
                extArq = "PNG";
            }else if (jpgBox.isSelected()) {
                extArq = "JPG";
            }
            */
            
            //Condições para setar o tamanho da imagem (jSlider)
            switch (jSliderTamanhoImagem.getValue()) {
                case 1:
                size = (int) px;
                break;
                case 2:
                size = (int) px * 2;
                break;
                case 3:
                size = (int) px * 3;
                break;
                case 4:
                size = (int) px * 4;
                break;
                case 5:
                size = (int) px * 5;
                break;
                case 6:
                size = (int) px * 6;
                break;
                case 7:
                size = (int) px * 7;
                break;
                case 8:
                size = (int) px * 8;
                break;
                case 9:
                size = (int) px * 9;
                break;
                case 10:
                size = (int) px * 10;
                break;
                default:
                break;
            }

            //Condições para setar o tamanho da imagem (jCheckbox)
            /*if (tam125Box.isSelected()) {
                size = size + 125;
            }else if (tam175Box.isSelected()) {
                size = size + 175;
            }else if (tam225Box.isSelected()) {
                size = size + 225;
            }*/
            
            /*
            //Criando e salvando o QR
            String nomeArquivo = txtParaNome.getText() + extArqNome;
            try {
                try (FileOutputStream f = new FileOutputStream(nomeArquivo)) {
                    ByteArrayOutputStream out = QRCode.from(txtParaQrCode.getText())
                    .to(ImageType.valueOf(extArq))
                    .withSize(size, size)
                    .stream();
                    f.write(out.toByteArray());
                    f.flush();
                    f.close();
                }
                JOptionPane.showMessageDialog(rootPane, "Arquivo " + nomeArquivo
                    + " foi gerado com sucesso!", "Arquivo gerado", JOptionPane.INFORMATION_MESSAGE);
            } catch (IOException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            */
            
            //Diálogo para salvar o QR gerado
            JFileChooser fc = new JFileChooser();
            //Obtem a resposta
            int rv = fc.showDialog(txtParaQrCode, null);
            if(rv == JFileChooser.APPROVE_OPTION){
                try{
                    //Obtem a rota e coloca a extensão do arquivo
                    String rota = fc.getSelectedFile().getAbsolutePath() + extArqNome;
                    //Cria o arquivo
                    fout = new FileOutputStream(new File(rota));
                    //Escreve o conteúdo do arquivo
                    fout.write(out.toByteArray());
                    
                    //Libera a memória
                    fout.flush();
                    fout.close();
                    
                    File f = new File("temp.png");
                    f.delete();
                    
                }catch (FileNotFoundException ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        } else if(/*txtParaNome.getText().equals("") & */txtParaQrCode.getText().equals("")
            || /*txtParaNome.getText().equals("") |*/ txtParaQrCode.getText().equals("")) {
            JOptionPane.showMessageDialog(null,"Informe o conteúdo do arquivo!",
                "Campo vazio", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnGerarQrCodeActionPerformed
    FileOutputStream fout;
    ByteArrayOutputStream out;
    private void btnLimparTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparTextoActionPerformed
        txtParaQrCode.setText(null);
    }//GEN-LAST:event_btnLimparTextoActionPerformed

    private void txtParaQrCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtParaQrCodeKeyReleased
        //Verifica se tem algo escrito
        if(txtParaQrCode.getText().equals("")){
            return;
        }
        
        //Pegando o texto escrito
        String texto = txtParaQrCode.getText();
        //Recebe o stream do QR gerado pela biblioteca QR
        out = QRCode.from(texto).withSize(247, 247).to(ImageType.PNG).stream();
        
        try{
            //Cria o arquivo
            fout = new FileOutputStream(new File("temp.png"));
            //Escreve o conteúdo do arquivo
            fout.write(out.toByteArray());
            //Libera a memória
            fout.flush();
            fout.close();
            
            //Mostra a imagem gerada
            //Lê a imagem
            BufferedImage meuQr = ImageIO.read(new File("temp.png"));
            //Desenha em um controle
            JLabel label = new JLabel(new ImageIcon(meuQr));
            //Obtem o canvas do JPanel para poder desenhar a imagem sobre ele
            Graphics g = jPanelVisualizador.getGraphics();
            //Desenha a imagem
            g.drawImage(meuQr, WIDTH, WIDTH, label);
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_txtParaQrCodeKeyReleased

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // Colocando ícone no System Tray
        initialize();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerarQrCode;
    private javax.swing.JButton btnLimparNome;
    private javax.swing.JButton btnLimparTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelConteudoQR;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelNomeArquivo;
    private javax.swing.JLabel jLabelTamanhoImagem;
    private javax.swing.JMenu jMenuArquivo;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuInfo;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JPanel jPanelFormatoImagem;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JPanel jPanelVisualizador;
    private javax.swing.JScrollPane jScrollPane1ConteudoQR;
    private javax.swing.JSlider jSliderTamanhoImagem;
    private javax.swing.JCheckBox jpgBox;
    private javax.swing.JCheckBox pngBox;
    private javax.swing.JTextField txtParaNome;
    private javax.swing.JTextArea txtParaQrCode;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagens/icon.png")));
    }
    
    private void setConfDefault() {
        //tam125Box.setSelected(true);
        pngBox.setSelected(true);
    }
    
    private void sendNotification() {
        Date date = new Date();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        System.out.println(dateFormat.format(date));
        
    }
}
